name = "CBindingGen"
uuid = "308a6e0c-0495-45e1-b1ab-67fb455a0d77"
authors = ["Keith Rutkowski <keith@analytech-solutions.com>"]
version = "0.2.0"

[deps]
CBinding = "d43a6710-96b8-4a2d-833c-c424785e5374"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
LLVM_jll = "86de99a1-58d6-5da7-8064-bd56ce2e322c"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[compat]
julia = "^1.3"
CBinding = "^0.8.2"
LLVM_jll = "6.0.1,8.0.1"
