name = "CBindingGen"
uuid = "308a6e0c-0495-45e1-b1ab-67fb455a0d77"
authors = ["Keith Rutkowski <keith@analytech-solutions.com>"]
version = "0.4.5"

[deps]
CBinding = "d43a6710-96b8-4a2d-833c-c424785e5374"
Clang_jll = "0ee61d77-7f21-5576-8119-9fcc46b10100"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[compat]
julia = "^1.5"
CBinding = "^0.9.0"
Clang_jll = "9.0.1,11.0.0,11.0.1"
