name = "CBindingGen"
uuid = "308a6e0c-0495-45e1-b1ab-67fb455a0d77"
authors = ["Keith Rutkowski <keith@analytech-solutions.com>"]
version = "0.1.0"

[deps]
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Todo = "b28a226c-6cff-11e9-1336-699fd753ab00"
CBinding = "d43a6710-96b8-4a2d-833c-c424785e5374"

[compat]
julia = "^1.1"
